name: Build and Deploy Hexo 
on: 
  push:
    branches:
      - master 
env:
  TZ: Asia/Shanghai

# 任务
jobs: 
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install Dependencies
        run: npm install

      # 生成静态文件
      - name: Generate pages
        run: |
          npm i hexo-cli -g 
          npm fund
          hexo g

      # 部署到 GitHub Pages
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
          commit-message: feat(posts):GitHub Actions Auto Builder Docs at ${{ env.NOW }}